### ISSUE TITLE
Incompatibility with rails upgrade

### ISSUE THREAD

**Issue by BrunaBelo** [prontolabs/pronto-fasterer#15]
I am having an issue with this gem. I updated rails from 4.2 to 5.0.5 and ruby from 2.3.7 to 2.4 and, when I try to run `bundle exec pronto run -f gitlab -c origin/master`, I am getting the following error:

```
.bundle/ruby/2.4.0/gems/sexp_processor-4.16.1/lib/sexp.rb:224:in `line': setting s(:rlist, s(:attrasgn, s(:const, :I18n), :default_locale=, s(:str, "pt-BR"))).line nil (ArgumentError)
```

I think that the issue is related with `pronto-faster` gem because when I remove It from the Gemfile, the command  `bundle exec pronto run -f gitlab -c origin/master` works without any problems.

I already tried to google It and I cound't find anything about this error. Do you have a suggestion about what could be the solution for it?

I'm using the following gems
```
  gem 'fasterer', '~> 0.10.0'
  gem 'pronto', '~> 0.10.0', require: false
  gem 'pronto-brakeman', '~> 0.10.0', require: false
  gem 'pronto-rubocop', '~> 0.10.0', require: false
  gem 'pronto-fasterer', '~> 0.10.0', require: false
```

**Comment by ashkulz** [comment]
@BrunaBelo can you check if this is still an issue with the latest version of `pronot-fasterer` and reopen if so?
