### ISSUE TITLE
Fasterer semantic version is too strict

### ISSUE THREAD

**Issue by hlascelles** [prontolabs/pronto-fasterer#16]
At the moment pronto-fasterer requires `~> 0.10.0`.

This rules out the new version 0.11.0: https://github.com/DamirSvrtan/fasterer/pull/106#issuecomment-1818204102

Can it be relaxed to `~> 0.10`? ie allow higher minor versions?

**Comment by KieranP** [comment]
@ashkulz  Any chance we could get a new release to support fasterer 0.11.0 ? This gem is holding back upgrading upgrading fasterer, which in turn is holding back from upgrading other dependant gems.

**Comment by ashkulz** [comment]
@hlascelles / @KieranP I'd be happy to accept a PR which bumps the maximum allowed version.

**Comment by hlascelles** [comment]
Looks like this one covered it... https://github.com/prontolabs/pronto-fasterer/pull/17

Thank you!

Can we get a new gem cut please?

**Comment by hlascelles** [comment]
I see you have, thanks 🙇. https://rubygems.org/gems/pronto-fasterer/versions/0.11.3
